import { push, ref, set } from "firebase/database";
import { database } from "../firebase.config";

const addProspect = async (
  prospectData: Record<string, any>
): Promise<string | null> => {
  try {
    const currentDate = new Date();
    const dateId = currentDate.toISOString().split("T")[0]; // Format YYYY-MM-DD
    const refPath = `prospect/${dateId}`;
    const newRef = push(ref(database, refPath)); // Create a new reference with a unique ID
    const uniqueId = newRef.key; // Get the unique ID generated by Firebase

    if (!uniqueId) {
      throw new Error("Failed to generate unique ID");
    }

    await set(newRef, prospectData);
    console.log("Prospect added successfully");
    return `${dateId}/${uniqueId}`;
  } catch (error) {
    console.error("Error adding prospect: ", error);
    return null;
  }
};

export default addProspect;
